name: task_queue

services:
  task-queue:
    container_name: task_queue
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    env_file:
      - .env
    volumes:
      - ../:/app/
    depends_on:
      - redis
    networks:
      - translate_service_network
    command: >
      celery -A celery_worker.app worker --loglevel=info
    tty: true
    restart: unless-stopped

  redis:
    image: redis:6.2-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - translate_service_network
    restart: unless-stopped

networks:
  translate_service_network:
    driver: bridge
